### PR TITLE
Add species

### PR DESCRIPTION
**Pull request by captainrandom**
https://github.com/Public-Tree-Map/public-tree-map-data-pipeline/issues/56
https://github.com/Public-Tree-Map/public-tree-map-data-pipeline/issues/36

addresses #56 and #36

# Screenshots
This shows the new species_id on the tree.json file:
Screen Shot 2019-11-26 at 12 35 21 AM

This shows the rows with new species ids (is this what you were expecting?):
Screen Shot 2019-11-25 at 11 54 50 PM

# What I did
- Added species_id to the tree.json
- Added a script to find rows from the tree_inventory dataset that have new species ids

### CODE REVIEW

**Comment by captainrandom** [comment]
Keep in mind that this is dependent on this cr getting pushed first: https://github.com/Public-Tree-Map/public-tree-map-data-pipeline/pull/57

**Comment by emillipede** [comment]
thank you so much @captainrandom! I wasn't sure about how to best implement a flag, but find_missing_species.py works! all of the trees in the screenshot are missing from the species attributes csv.

can you please explain what happens when it finds a missing species and then goes to the last step `print(new_species_tree_inventory_df.to_csv)`? will there be a new csv (that lists trees whose species IDs don't appear in the species attributes csv) in the repository's data folder? if that's the case, is it possible to build in some kind of reporting (to know that new tree species need to be documented)? for example, could new entries to that csv be automatically made into new issues?

re #57 , is it OK to merge?

thank you again!

**Comment by captainrandom** [comment]
So first thing this using the pandas dataframe api #itsamazing! Basically, they try to make an object (in code) act like a sql table (somewhat).

If you know how sql works, then you should be good. (ps. It's a super handy skill for data manipulation). Otherwise, you should read this article (specifically about the left join section, because that's what I'm using in the code above):

https://blog.codinghorror.com/a-visual-explanation-of-sql-joins/

If none of that made any sense, ask more questions and I'll see where I can help you out.

First thing is I load the datasets, pandas can read CSVs into data frames (the rows and columns in the csv directly translate to the rows and columns in the dataframe). For the url part, later versions of pandas can download data from a url and parse the data into a dataframe.

How this works is I do a left join between the "Species ID" in both the species_attributes.csv and the trees_inventory datasets.

Here is another article of someone doing joins, except this time with pandas:



There are probably a couple of things I should probably do before pushing:
1) add paramters for the url and the species_attributes.csv file path
2) add comments

**Comment by captainrandom** [comment]
1 & 2 above are done now.

**Comment by emillipede** [comment]
thank you for the link and description of how the dataframe and joins work, it was really helpful. I know little bit about how sql works, I've used mysql, but I'd like to understand it better. 

the city arborists don't regularly plant new tree species or track/report them, but it seems to happen at least once a month (in the last 6 months, there have been about 15 new trees species or varieties).

in this PR, the find_missing_species.py script isn't part of the automated pipeline, right? it would need to be run from the command line? I did mean automatically generating github issues, but I get your concern about it. what do you think about automatically running the script as part of circle ci and adding in something like mailgun to send email notifications if it returns any missing species?

I'd like to keep circle ci, at least for now. it makes the deployment process really easy, though it does create some extra complexity. I could add some documentation to the readme to clarify that any new dependencies need to be added to both systems. how does that sound? please let me know what you think.

thank you again!!!

**Comment by captainrandom** [comment]
I totally need to re-review that this still works after #69 goes out.

**Pull request closed without merging**
